### ISSUE TITLE
部门管理员不能查看漏洞

### ISSUE THREAD

**Issue by chuanwei** [creditease-sec/insight#23]
部门管理员不能查看本部门的漏洞返回如下：
Sorry,internal server error! 
错误日志如下：
[2018-04-29 11:38:00,818] ERROR in app: Exception on /srcpm/src/vul_notify_list [GET]
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib/python2.7/site-packages/flask_login.py", line 792, in decorated_view
    return func(*args, **kwargs)
  File "/opt/webapp/srcpm/app/src/views.py", line 356, in vul_notify_list
    return render_template('src/vul_notify_list.html', vul_report_list=vul_report_list, opt_label=opt_label)
UnboundLocalError: local variable 'vul_report_list' referenced before assignment
@zwalts @liusec

**Comment by qiuleilei** [comment]
遇到同样的问题，请问解决了吗？

**Comment by alexanderhawl** [comment]
这个需要改下代码。将srcpm/app/src/views.py中， 判断普通用户是否为部门经理，部门经理有权限查看部门所有漏洞这段代码改为:
elif current_user.role_name == u'普通用户':
		# 判断普通用户是否为部门经理，部门经理有权限查看部门所有漏洞
		department_list = Depart.query.filter_by(email=current_user.email).all()
		vul_report_list = []
		if department_list:
			#vul_report_list = []
			for department in department_list:
				vul_report_list += query.filter(Asset.department==department.department).all()
		else:
			vul_report_list+= query.filter(Asset.owner.like("%" + current_user.email + "%")).all()
