### ISSUE TITLE
drops 搜索处，对搜索空字符串未做判断

### ISSUE THREAD

**Issue by ghost** [creditease-sec/insight#54]
也不算个问题。

drops 搜索处，搜索空字符串未做判断
![image](https://user-images.githubusercontent.com/11814103/56123778-c624fa00-5fa7-11e9-876c-2d8e1d0c0540.png)

查询出错

![image](https://user-images.githubusercontent.com/11814103/56123804-cf15cb80-5fa7-11e9-8753-274b9d6a5bab.png)

```
[2019-04-15 09:53:02,476] ERROR in app: Exception on /srcpm/drops/search [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/webapp/srcpm/app/drops/views.py", line 133, in search
    searchresult = Postdrop.query.search(searchword)
  File "/opt/webapp/srcpm/app/drops/models.py", line 99, in search
    q = reduce(db.and_, criteria)
TypeError: reduce() of empty sequence with no initial value
```

**Comment by shimmerming** [comment]
已经修复，谢谢对洞察系统的关注
